name: Run Tests

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install dependencies for the server
      - name: Install server dependencies
        run: |
          cd server
          npm install

      # Step 4: Start the server
      - name: Start the server
        run: |
          cd server
          npm run start &
        env:
          NODE_ENV: test

      # Step 5: Wait for the server to start
      - name: Wait for server to start
        run: sleep 10

      # Step 6: Install dependencies for tests
      - name: Install test dependencies
        run: |
          cd tests
          npm install

      # Step 7: Run tests
      - name: Run tests
        run: |
          cd tests
          npm run test